### ISSUE TITLE
scribe output should be json compliant, not "kind-of json"

### ISSUE THREAD

**Issue by atheurer** [cloud-bulldozer/scribe#6] opened 2018-10-10 14:00 UTC
Right now the output does not adhere correctly to json format.  For example, the output:

{
    "module": "yum_repos",
    "source_type": "stockpile",
    "host": "perf36",
    "scribe_uuid": "a954fffa-008e-42bb-8a69-4eec03901a35",
    "repo_name": "copr-pbench",
    "repo_state": 1,
    "base_url": "http://mirror.centos.org/centos/$releasever/copr-pbench/$basearch/"
}
{
    "module": "yum_repos",
    "source_type": "stockpile",
    "host": "perf36",
    "scribe_uuid": "a954fffa-008e-42bb-8a69-4eec03901a35",
    "repo_name": "dell-system-update_dependent",
    "repo_state": 1,
    "base_url": "http://mirror.centos.org/centos/$releasever/dell-system-update_dependent/$basearch/"
}

This will fail a json validator like https://jsonlint.com

There are also other issues where non-document data is output (warnings, errors, etc) which will disqualify the output as json.

**Comment by aakarshg** [comment] 2018-10-10 15:16
@atheurer. There are 2 separate documents in there, if you take just one document. Let's say 
```json
{
"module": "yum_repos",
"source_type": "stockpile",
"host": "perf36",
"scribe_uuid": "a954fffa-008e-42bb-8a69-4eec03901a35",
"repo_name": "dell-system-update_dependent",
"repo_state": 1,
"base_url": "http://mirror.centos.org/centos/$releasever/dell-system-update_dependent/$basearch/"
}
```
and try to validate, it'll pass. 

There will be non document data that'll be output if scribe is being used as a python library:
```
from transcribe.render import transcribe
for scribe_object in transcribe('/tmp/stockpile.json','stockpile'):
    print(scribe_object)
```
If you look at [render.py,](https://github.com/redhat-performance/scribe/blob/master/transcribe/render.py#L40) you'll see that `yield` is being used to generate documents. So instead of just using print(scribe_object) we can verify if it's a document and then print it or in ideal case index it into ES.

**Comment by atheurer** [comment] 2018-10-10 15:42
Yes, I am aware a single doc will pass :) 

My issue was that the output was mixed, and not adhering strictly to json.  If it was 100% json, we'd have an array as output, with each document separated with a ",".  And so output from "scribe" could not be fed directly into another utility which expects pure json.  If you are stating that there's no guarantee of a 100% compliant json output (from scribe command), and the user must further parse this output, then I guess I will go forward with that assumption, and this issue can be closed.

**Comment by aakarshg** [comment] 2018-10-10 19:04
The issue with having all documents in an array is helpful if we want to index all documents in the array go into same index, however that's not the case with scribe. We leave it to the user to index a document or discard it, and if being indexed, upto user to deal with which index it needs to go and such. More importantly, using generators is more efficient use of memory. I think there is some confusion that is caused by looking at scribe command's output, yes scribe command produces warnings and errors in output. But in all our cases we would be using scribe as a python library:
```
from transcribe.render import transcribe
for scribe_object in transcribe('/tmp/stockpile.json','stockpile'):
    print(scribe_object)
```
The scribe_object is always a 100% JSON document, the errors are printed out yes but that's because the print function is called [here](https://github.com/redhat-performance/scribe/blob/master/transcribe/render.py#L38) but as you see it's not being yielded or returned. So thus when you deal with scribe_object in the above snippet it'll be a validated json document. 

I hope that clears all confusion, sorry for causing confusion.

**Comment by aakarshg** [comment] 2018-10-10 19:09
Closing this issue as the functionality is correct and transcribe function always generates a JSON document if used as a python library. What is being printed will not be passed on to caller, but only the return/yield object would be. Hope it makes sense. Please reach out to me if it doesn't make sense or requires further clarity

**Closed as completed by aakarshg** 2018-10-10 19:09 UTC
